version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: farmacia_db_local
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-farmacia123}
      POSTGRES_DB: ${POSTGRES_DB:-farmacia_vallenar}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
